package io.kalypso.scheduler.api.v1alpha1.spec;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Desired state of an {@code AssignmentPackage} resource.
 *
 * <p>An AssignmentPackage is generated by the {@code AssignmentReconciler} and
 * contains the fully rendered manifests for a specific (ClusterType, DeploymentTarget)
 * pair. The manifests are grouped by role (reconciler, namespace, config) and each
 * group carries a content type describing how the strings should be interpreted.
 *
 * <p>The {@code GitOpsRepoReconciler} aggregates all AssignmentPackages in the
 * namespace and opens a GitHub PR delivering the rendered manifests to the target
 * GitOps repository.
 *
 * <p>Example YAML:
 * <pre>
 * spec:
 *   reconcilerManifests:
 *     - "apiVersion: kustomize.toolkit.fluxcd.io/v1\nkind: Kustomization\n..."
 *   reconcilerManifestsContentType: yaml
 *   namespaceManifests:
 *     - "apiVersion: v1\nkind: Namespace\n..."
 *   namespaceManifestsContentType: yaml
 *   configManifests: []
 *   configManifestsContentType: yaml
 * </pre>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AssignmentPackageSpec {

    /**
     * Label key set by the {@code AssignmentReconciler} to identify which
     * {@code ClusterType} produced this package.
     */
    public static final String CLUSTER_TYPE_LABEL = "scheduler.kalypso.io/clusterType";

    /**
     * Label key set by the {@code AssignmentReconciler} to identify which
     * {@code DeploymentTarget} this package targets.
     */
    public static final String DEPLOYMENT_TARGET_LABEL = "scheduler.kalypso.io/deploymentTarget";

    /**
     * Rendered reconciler manifests (one string per manifest file).
     * Typically contains Flux {@code Kustomization} or other reconciler resources.
     */
    @JsonProperty("reconcilerManifests")
    private List<String> reconcilerManifests = new ArrayList<>();

    /**
     * Content type of the {@link #reconcilerManifests} strings,
     * e.g. {@link ContentType#YAML} or {@link ContentType#SH}.
     */
    @JsonProperty("reconcilerManifestsContentType")
    private ContentType reconcilerManifestsContentType;

    /**
     * Rendered namespace-provisioning manifests (one string per manifest file).
     * Typically contains namespace definitions and RBAC resources.
     */
    @JsonProperty("namespaceManifests")
    private List<String> namespaceManifests = new ArrayList<>();

    /**
     * Content type of the {@link #namespaceManifests} strings,
     * e.g. {@link ContentType#YAML} or {@link ContentType#SH}.
     */
    @JsonProperty("namespaceManifestsContentType")
    private ContentType namespaceManifestsContentType;

    /**
     * Rendered configuration manifests (one string per manifest file).
     * Typically contains ConfigMap or envfile resources carrying runtime config.
     */
    @JsonProperty("configManifests")
    private List<String> configManifests = new ArrayList<>();

    /**
     * Content type of the {@link #configManifests} strings,
     * e.g. {@link ContentType#YAML} or {@link ContentType#SH}.
     */
    @JsonProperty("configManifestsContentType")
    private ContentType configManifestsContentType;

    /**
     * Returns the rendered reconciler manifests list.
     *
     * @return the reconciler manifests; never {@code null}
     */
    public List<String> getReconcilerManifests() {
        return reconcilerManifests;
    }

    /**
     * Sets the rendered reconciler manifests list.
     *
     * @param reconcilerManifests the list of rendered strings; {@code null} is treated as empty
     */
    public void setReconcilerManifests(List<String> reconcilerManifests) {
        this.reconcilerManifests = reconcilerManifests != null ? reconcilerManifests : new ArrayList<>();
    }

    /**
     * Returns the content type for reconciler manifests.
     *
     * @return the {@link ContentType}, or {@code null} if not set
     */
    public ContentType getReconcilerManifestsContentType() {
        return reconcilerManifestsContentType;
    }

    /**
     * Sets the content type for reconciler manifests.
     *
     * @param reconcilerManifestsContentType the {@link ContentType}
     */
    public void setReconcilerManifestsContentType(ContentType reconcilerManifestsContentType) {
        this.reconcilerManifestsContentType = reconcilerManifestsContentType;
    }

    /**
     * Returns the rendered namespace manifests list.
     *
     * @return the namespace manifests; never {@code null}
     */
    public List<String> getNamespaceManifests() {
        return namespaceManifests;
    }

    /**
     * Sets the rendered namespace manifests list.
     *
     * @param namespaceManifests the list of rendered strings; {@code null} is treated as empty
     */
    public void setNamespaceManifests(List<String> namespaceManifests) {
        this.namespaceManifests = namespaceManifests != null ? namespaceManifests : new ArrayList<>();
    }

    /**
     * Returns the content type for namespace manifests.
     *
     * @return the {@link ContentType}, or {@code null} if not set
     */
    public ContentType getNamespaceManifestsContentType() {
        return namespaceManifestsContentType;
    }

    /**
     * Sets the content type for namespace manifests.
     *
     * @param namespaceManifestsContentType the {@link ContentType}
     */
    public void setNamespaceManifestsContentType(ContentType namespaceManifestsContentType) {
        this.namespaceManifestsContentType = namespaceManifestsContentType;
    }

    /**
     * Returns the rendered config manifests list.
     *
     * @return the config manifests; never {@code null}
     */
    public List<String> getConfigManifests() {
        return configManifests;
    }

    /**
     * Sets the rendered config manifests list.
     *
     * @param configManifests the list of rendered strings; {@code null} is treated as empty
     */
    public void setConfigManifests(List<String> configManifests) {
        this.configManifests = configManifests != null ? configManifests : new ArrayList<>();
    }

    /**
     * Returns the content type for config manifests.
     *
     * @return the {@link ContentType}, or {@code null} if not set
     */
    public ContentType getConfigManifestsContentType() {
        return configManifestsContentType;
    }

    /**
     * Sets the content type for config manifests.
     *
     * @param configManifestsContentType the {@link ContentType}
     */
    public void setConfigManifestsContentType(ContentType configManifestsContentType) {
        this.configManifestsContentType = configManifestsContentType;
    }
}
